### ISSUE TITLE
Sección de noticias de MedMIS - no se visualizan las fechas

### ISSUE THREAD

**Issue by isapozuelo** [GeographicaGS/IUCN-reporting-www#1]
No se visualiza el icono de fecha, creo que está tirando de la versión de desarrollo y no de la de producción y por eso no lo encuentra:
Esta es la url que intenta buscar: http://www.dev.iucn-medmis.org/img/IUCN_w_icon_fecha-hora.png
Esta sí funciona: http://www.iucn-medmis.org/img/IUCN_w_icon_fecha-hora.png

![image](https://cloud.githubusercontent.com/assets/12248150/16247718/6bc96d64-380b-11e6-941e-c12f669fc2ec.png)

**Comment by alasarr** [comment]
@padawannn @neokore echad un vistazo a esto. Debemos solucionarlo mañana. Buenas noches!

**Comment by padawannn** [comment]
Arreglado

**Comment by alasarr** [comment]
@isapozuelo se ha notificado esto a Mar. Si es así cierra please.

**Comment by alasarr** [comment]
@isapozuelo cierra please.

**Comment by alasarr** [comment]
¿Se le ha notificado a mar?

**Comment by isapozuelo** [comment]
Sí, notifiqué a Mar.
Perdona @alasarr , hasta hace una semana no recibía en la bandeja de entrada las notificaciones de Github.

**Comment by alasarr** [comment]
Great! No problem!
