### ISSUE TITLE
Cambio iconos de avistamientos

### ISSUE THREAD

**Issue by alasarr** [GeographicaGS/IUCN-reporting-www#2]
En palabras de Mar:

Los avistamientos estan ahora en cruces de color verde y hablaramos de ponerlo en otro color (quizas rojo) que destacaran mas con el mapa de fondo. Ahora son difíciles de visualizar

Dijistes que lo podias cambiar sin problema

**Comment by alasarr** [comment]
Esto deberíamos pegarle un vistazo mañana. Nos va a dar aire con las aplicaciones móviles

**Comment by josegilg** [comment]
OK, lo veo luego.

pd. Cómo se expresa, que maravilla.

**Comment by alasarr** [comment]
Pues ese está bien... El correo empezó por un "Haz lo del color de los avistamientos"

**Comment by josegilg** [comment]
@alasarr me das mas detalles de qué tenemos que hacer con los iconos? Los avistamientos adoptan un color dependiendo de la categoría al que pertenece... Si es verde, es un alga.

**Comment by alasarr** [comment]
@isapozuelo ¿puedes aclarar esto con Mar? @josegilg tiene razón en que el icono se ve. ¿Por qué dice que no se ve?

El icono hace referencia a una categoría: alga y esto se refleja en diferentes partes. No vemos el poner el alga en rojo y reflejarlo en toda la aplicación.

Dile que hemos hecho pruebas y queda muy raro.

**Comment by isapozuelo** [comment]
![img_05072016_131304](https://cloud.githubusercontent.com/assets/12248150/16583118/b46afc38-42b3-11e6-8673-dd2fb90411b3.png)

**Comment by josegilg** [comment]
Es cierto que, en determinados contextos de zoom y debido al estilo del mapa base (con áreas naturales en verdes), los iconos de algas se pierdan. 

Propongo variar el color de esta categoría para hacerla más destacable, pero siempre en tono verde –más intensa–.

@isapozuelo consúltale a Mar si esta opción le satisface. 
¿Tú que opinas @alasarr ?

**Comment by alasarr** [comment]
Me parece bien

**Comment by isapozuelo** [comment]
@josegilg perfecto, como te comenté, Mar me dijo que intentásemos poner más intensas todas las categorías, porque la de peces (azul) tampoco la ve bien con el fondo marino.

**Comment by josegilg** [comment]
Set de nuevos iconos para sustituir: mapa (normal e histórico) y filtro. 

Los archivos tienen los mismos nombres. 

[IMGs_marcadores-2016.zip](https://github.com/GeographicaGS/IUCN-reporting-www/files/369336/IMGs_marcadores-2016.zip)

**Comment by padawannn** [comment]
@alasarr @isapozuelo ya están subido los nuevos iconos en producción. Es muy importante decirle a Mar que tiene que limpiar las cachés del navegador porque sino va a ver los antiguos

**Comment by isapozuelo** [comment]
Muy bien. @alasarr  ¿quieres que se lo diga a Mar?

**Comment by alasarr** [comment]
Yes! Y cierra si lo ves bien.
