### ISSUE TITLE
Redes de protección

### ISSUE THREAD

**Issue by isapozuelo** [GeographicaGS/IUCN-reporting-www#24]
La capa de redes de protección no se carga:

- [x] en el mapa principal.

![image](https://cloud.githubusercontent.com/assets/12248150/25991285/fb979334-3702-11e7-808b-cc221c2e753d.png)

- [x] En el mapa de dar de alta un avistamiento normal

- [x] En el mapa de dar de alta un avistamiento de colaborador

![image](https://cloud.githubusercontent.com/assets/12248150/25991330/11176fd6-3703-11e7-9667-cd227b651dda.png)

Cuándo señalo un punto que tiene AMP + Redes de protección dentro del mapa de alta de avistamientos, me reconoce ambas, aunque no se haya visualizado la capa:
![image](https://cloud.githubusercontent.com/assets/12248150/25991421/613cf1a2-3703-11e7-94c9-2296abefc2a4.png)

Sin embargo, cuándo consulto el avistamiento, solo aparece la AMP

![image](https://cloud.githubusercontent.com/assets/12248150/25991448/740fe028-3703-11e7-915a-a3e151cd4c30.png)

**Comment by javimudi** [comment]
Lo último sí consigo reproducirlo, a mí también me pasa. Lo reviso. Del resto, sospecho que es un tema de cachés o algo.

**Comment by javimudi** [comment]
Listo, corregido.
