### ISSUE TITLE
Modificar logos

### ISSUE THREAD

**Issue by isapozuelo** [GeographicaGS/IUCN-reporting-www#4]
Cambiar los logos de MedMIS.
Quitar los que están en "Financiada por" y poner el logo que adjunto
El resto de logos se quedan como están ("con el apoyo de" y "en colaboración con")

![mava_logo_for_office](https://cloud.githubusercontent.com/assets/12248150/19968241/0bb07f98-a1d4-11e6-89b3-a145722c3171.jpg)

**Comment by neokore** [comment]
Esto afectaría a las aplicaciones móviles?

**Comment by isapozuelo** [comment]
¿En las aplicaciones están esos logos? Supongo que sí, que también habría que cambiarlas, pregúntale a Alberto.

**Comment by padawannn** [comment]
@isapozuelo ya está el logo, en cuanto a las aplicaciones móviles yo me haría el loco
