### ISSUE TITLE
Internal error al crear nuevo avistamiento

### ISSUE THREAD

**Issue by isapozuelo** [GeographicaGS/IUCN-reporting-www#5]
Al crear un nuevo avistamiento da un internal error. 

Como posibilidad: El otro día Alberto y yo incluimos en la base de datos 200 avistamientos nuevos ¿puede ser un error con la primary key? que no se esté generando bien el serial con un next value.

**Comment by padawannn** [comment]
Que lista eres @isapozuelo, ya está arreglado ciérrala cuando quieras
